### Netlify Function (Default)
GET http://localhost:8888/.netlify/functions/hello

### Netlify Function (Default) with data
POST http://localhost:8888/.netlify/functions/hello
Content-Type: application/json

{
  "message": "Hey this is cool! 😎"
}

### Netlify Function (Background)
GET http://localhost:8888/.netlify/functions/hello-background


### Netlify Function (Background) FAIL
POST http://localhost:8888/.netlify/functions/hello-background-fail

### Netlify Function (Background) Practical Example
POST http://localhost:8888/.netlify/functions/send-pdf-background
Content-Type: application/json

{
  "content": "We're doing this LIVE at UE! 💪",
  "destination": "me@dorelljames.com"
}